
server:
  error:
    include-stacktrace: never
    include-message: always

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    username: demo
    password: demo
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    database: postgresql
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        #jdbc:
        #  lob:
        #    non_contextual_creation: true


app:
  max-new-tasks: 20